### ISSUE TITLE
agree on game resolution being 700 x 1100

### ISSUE THREAD

**Issue by neil-justice** [ProjectElves/SoftwareEngineering#17]
-must be a multiple of 32
-we are thinking 800x576?

**Comment by neil-justice** [comment]
-must be a multiple of 32
-we are thinking 800x576?

**Comment by ericsonguk** [comment]
If it's 64x64 it might be worth making it bigger..
Is 1280x640 bit too much..?
If so, how about 960x640?

**Comment by nikopapp** [comment]
Well I actually am working with 704x1150 which is multiple of 64
